pkg_origin=cosmos

pkg_name=ca-certificates
pkg_version=20161130
pkg_description='Common CA certificates'
pkg_upstream_url='http://packages.qa.debian.org/c/ca-certificates.html'
pkg_license=('MPL' 'GPL')
pkg_deps=('bash' 'run-parts' 'openssl' 'findutils' 'coreutils' 'sed')
pkg_build_deps=('ruby' 'python2')
install=ca-certificates.install
backup=('etc/ca-certificates.conf')
pkg_source=("http://ftp.debian.org/debian/pool/main/c/${pkg_name}/${pkg_name}_${pkg_version}.tar.xz")
pkg_shasum=('1a0a3a1b3390dc83affed4b0c2ae1c05')

do_build() {
  cd ${pkg_name}

  make
}

do_package() {
  cd ${pkg_name}

  install -d -m755 ${pkg_prefix}/{etc/ca-certificates/update.d,usr/{sbin,share/ca-certificates},etc/ssl/certs}
  make install DESTDIR=${pkg_prefix}
  install -D -m644 sbin/update-ca-certificates.8 ${pkg_prefix}/usr/share/man/man8/update-ca-certificates.8

  (
    echo "# Automatically generated by ${pkg_name}-${pkg_version}-${pkgrel}"
    echo "# see update-ca-certificates man page"
    echo "# "
    cd ${pkg_prefix}/usr/share/ca-certificates
    find . -name '*.crt' | sort | cut -b3-
  ) > ${pkg_prefix}/etc/ca-certificates.conf
}

